apiVersion: v1
kind: Pod
metadata:
  name: k8-pod
  labels:
    app: k8-pod
spec:
  containers:
  - name: k8-pod
    image: k8-img:v1
    env:
     - name: SPRING_PROFILES_ACTIVE
       value: dev    
    volumeMounts:
    - name: k8-mount
      mountPath: /env
  volumes:
    - name: k8-mount
      configMap:
        name: k8-config
        items:
        - key: application.yaml
          path: application.yaml
  restartPolicy: Never 