### kubectl create secret generic k8-secret --from-file=./my-secrets/

apiVersion: v1
data:
  k8-secret-dev.yaml: c2VjcmV0Og0KICBrZXk6IGRldi1zZWNyZXQ=
  k8-secret-prod.yaml: c2VjcmV0Og0KICBrZXk6IHByb2Qtc2VjcmV0
  k8-secret.yaml: c2VjcmV0Og0KICBrZXk6IGRlZi1zZWNyZXQ=
kind: Secret
metadata:
  name: k8-secret
  namespace: default